"""
Preflight contextual retrieval — Anthropic's technique adapted for Preflight.

Contextual retrieval prepends chunk-specific explanatory context (generated by an LLM)
to each chunk before embedding and indexing. This reduces retrieval failure rates by
35-67% (Anthropic research, combined with BM25 + reranking).

For Preflight, this is critical because:
- Regulatory chunks lose context when split (which regulation? which chapter?)
- ArchiMate elements need their graph context to be retrievable by concept
- Persona-scoped queries need domain-grounded context ("for the Security persona...")

Design decisions:
- Context is generated ONCE during ingestion, not at query time
- Context is stored alongside the chunk text in pgvector
- Different context templates per content type (regulatory, archimate, vendor, tabular)
- Context is bilingual (NL/EN) when the source document is bilingual
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Protocol, Sequence

from preflight.llm.client import LLMClient, CallOpts


CONTEXT_TEMPLATES = {
    "regulatory": (
        "Below is a chunk from a {language} regulatory document about {doc_title}. "
        "This chunk is from section {section} and covers {topic}. "
        "It is relevant to the following domains: {domains}. "
        "Chunk content:\n---\n{chunk}\n---\n"
        "Brief context (2-3 sentences) explaining what this chunk says, "
        "which regulation it belongs to, and what concepts it defines:"
    ),
    "archimate": (
        "Below is a chunk from the hospital's ArchiMate model. "
        "It describes {element_type} '{element_name}' which {element_desc}. "
        "This element has relationships: {relationships}. "
        "Chunk content:\n---\n{chunk}\n---\n"
        "Brief context (2-3 sentences) explaining this element's role in the architecture:"
    ),
    "vendor": (
        "Below is a chunk from a vendor document: {doc_title}. "
        "It covers {topic} and is relevant to domains: {domains}. "
        "The vendor is {vendor_name}. "
        "Chunk content:\n---\n{chunk}\n---\n"
        "Brief context (2-3 sentences) summarizing this chunk's claims and relevance:"
    ),
    "tabular": (
        "Below is a data row from a spreadsheet ({doc_title}). "
        "Columns: {columns}. This row represents: {row_desc}. "
        "Chunk content:\n---\n{chunk}\n---\n"
        "Brief context (2-3 sentences) explaining what this data represents:"
    ),
    "policy": (
        "Below is a chunk from the hospital's {doc_title} policy document. "
        "Section: {section}. Applies to: {domains}. "
        "Chunk content:\n---\n{chunk}\n---\n"
        "Brief context (2-3 sentences) explaining this policy requirement and its scope:"
    ),
    "generic": (
        "Below is a chunk from: {doc_title}. "
        "Chunk content:\n---\n{chunk}\n---\n"
        "Brief context (2-3 sentences) summarizing the key information in this chunk:"
    ),
}


@dataclass
class ContextualizedChunk:
    original_text: str
    context_prefix: str
    full_text: str
    chunk_index: int
    content_type: str
    source_id: str
    metadata: dict = field(default_factory=dict)


class ContextGenerator(Protocol):
    async def generate(self, chunk: str, content_type: str, metadata: dict) -> str: ...


class LLMContextGenerator:
    """Generate contextual prefixes using an LLM.

    Uses the light tier — this is preprocessing, not assessment reasoning.
    Prompt caching makes this cheap (~$1/M tokens with Claude, free with local Ollama).
    """

    def __init__(self, client: LLMClient, max_context_tokens: int = 100):
        self.client = client
        self.max_context_tokens = max_context_tokens

    async def generate(self, chunk: str, content_type: str, metadata: dict) -> str:
        template = CONTEXT_TEMPLATES.get(content_type, CONTEXT_TEMPLATES["generic"])

        prompt = template.format(
            chunk=chunk[:2000],
            doc_title=metadata.get("doc_title", "unknown document"),
            section=metadata.get("section", "unknown section"),
            topic=metadata.get("topic", ""),
            domains=metadata.get("domains", ""),
            language=metadata.get("language", "nl"),
            element_type=metadata.get("element_type", ""),
            element_name=metadata.get("element_name", ""),
            element_desc=metadata.get("element_desc", ""),
            relationships=metadata.get("relationships", ""),
            vendor_name=metadata.get("vendor_name", ""),
            columns=metadata.get("columns", ""),
            row_desc=metadata.get("row_desc", ""),
        )

        opts = CallOpts(
            temperature=0.1,
            max_tokens=self.max_context_tokens,
        )

        response = await self.client.call(
            system="You generate brief, factual context for document chunks. Be concise and accurate. Never fabricate information. State what the chunk contains, not what you wish it contained.",
            user=prompt,
            opts=opts,
        )

        context = response.text.strip()

        if len(context) > 500:
            context = context[:497] + "..."

        return context


class StaticContextGenerator:
    """Generate contextual prefixes without an LLM — using metadata only.

    For Phase 1 without a running LLM, or for pre-indexed content where
    metadata is already rich enough (ArchiMate exports, regulatory databases).
    """

    def __init__(self):
        self._templates = {
            "regulatory": "[{doc_title}, {section}] {topic}. Domains: {domains}. ",
            "archimate": "[ArchiMate {element_type}: {element_name}] {element_desc}. Relationships: {relationships}. ",
            "vendor": "[{doc_title}, {vendor_name}] {topic}. Domains: {domains}. ",
            "tabular": "[{doc_title}, row: {row_desc}] Columns: {columns}. ",
            "policy": "[{doc_title}, {section}] Applies to: {domains}. ",
            "generic": "[{doc_title}] ",
        }

    async def generate(self, chunk: str, content_type: str, metadata: dict) -> str:
        template = self._templates.get(content_type, self._templates["generic"])

        context = template.format(
            doc_title=metadata.get("doc_title", "unknown"),
            section=metadata.get("section", "unknown section"),
            topic=metadata.get("topic", ""),
            domains=metadata.get("domains", ""),
            language=metadata.get("language", "nl"),
            element_type=metadata.get("element_type", ""),
            element_name=metadata.get("element_name", ""),
            element_desc=metadata.get("element_desc", ""),
            relationships=metadata.get("relationships", ""),
            vendor_name=metadata.get("vendor_name", ""),
            columns=metadata.get("columns", ""),
            row_desc=metadata.get("row_desc", ""),
        )

        return context.strip()


async def contextualize_chunks(
    chunks: list[str],
    content_type: str,
    metadata_list: list[dict],
    generator: ContextGenerator,
    source_id: str = "",
) -> list[ContextualizedChunk]:
    """Add contextual prefixes to a list of chunks.

    This is the main entry point for the contextual retrieval pipeline.
    Each chunk gets a context prefix generated by the ContextGenerator,
    then the full_text (context + original) is what gets embedded.
    """
    results: list[ContextualizedChunk] = []

    for i, chunk in enumerate(chunks):
        meta = metadata_list[i] if i < len(metadata_list) else {}

        context_prefix = await generator.generate(chunk, content_type, meta)

        full_text = f"{context_prefix}\n{chunk}"

        results.append(
            ContextualizedChunk(
                original_text=chunk,
                context_prefix=context_prefix,
                full_text=full_text,
                chunk_index=i,
                content_type=content_type,
                source_id=source_id or meta.get("source_id", ""),
                metadata=meta,
            )
        )

    return results
