"""initial_schema

Revision ID: 7dbce67b87f1
Revises: 
Create Date: 2026-04-11 19:54:24.167515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbce67b87f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('context_prefix', sa.Text(), nullable=True),
    sa.Column('enriched_keyword', sa.Text(), nullable=False),
    sa.Column('enriched_semantic', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), server_default='internal', nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunk_source', 'knowledge_chunk', ['source_id'], unique=False)
    op.create_index('idx_chunk_type', 'knowledge_chunk', ['content_type'], unique=False)
    op.create_table('persona_calibration',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('perspective_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_assessments', sa.Integer(), nullable=False),
    sa.Column('approve_count', sa.Integer(), nullable=False),
    sa.Column('conditional_count', sa.Integer(), nullable=False),
    sa.Column('concern_count', sa.Integer(), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('override_count', sa.Integer(), nullable=False),
    sa.Column('override_rate', sa.Float(), nullable=True),
    sa.Column('override_decisions', sa.JSON(), nullable=True),
    sa.Column('predictions_correct', sa.Integer(), nullable=False),
    sa.Column('predictions_wrong', sa.Integer(), nullable=False),
    sa.Column('retrospective_accuracy', sa.Float(), nullable=True),
    sa.Column('alignment_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('recommended_change', sa.Text(), nullable=True),
    sa.Column('assessment_ids', sa.JSON(), nullable=True),
    sa.Column('retrospective_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_name', 'perspective_id', 'period_start', 'period_end')
    )
    op.create_table('persona_version',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('persona_count', sa.Integer(), nullable=False),
    sa.Column('definition_hash', sa.String(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entra_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('clearance_level', sa.String(), nullable=False),
    sa.Column('clinical_access', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entra_id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assessments_count', sa.Integer(), nullable=False),
    sa.Column('approval_rate', sa.Float(), nullable=True),
    sa.Column('open_conditions', sa.Integer(), nullable=False),
    sa.Column('nen7510_status', sa.String(), nullable=True),
    sa.Column('nen7512_status', sa.String(), nullable=True),
    sa.Column('nen7513_status', sa.String(), nullable=True),
    sa.Column('aivg_status', sa.String(), nullable=True),
    sa.Column('dpa_in_place', sa.Boolean(), nullable=False),
    sa.Column('dpia_required', sa.Boolean(), nullable=True),
    sa.Column('sbom_available', sa.Boolean(), nullable=False),
    sa.Column('sbom_format', sa.String(), nullable=True),
    sa.Column('systems_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_log', ['actor_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_assessment', 'audit_log', ['assessment_id'], unique=False)
    op.create_index('idx_audit_type', 'audit_log', ['event_type', 'timestamp'], unique=False)
    op.create_table('knowledge_source',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('persona_relevance', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index('idx_knowledge_type', 'knowledge_source', ['source_type'], unique=False)
    op.create_table('request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('impact_level', sa.String(), nullable=False),
    sa.Column('triage_floor_applied', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('adaptive_fields', sa.JSON(), nullable=True),
    sa.Column('landscape_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('system',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('archimate_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('lifecycle_status', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('biv_b', sa.SmallInteger(), nullable=True),
    sa.Column('biv_i', sa.SmallInteger(), nullable=True),
    sa.Column('biv_v', sa.SmallInteger(), nullable=True),
    sa.Column('dr_tier', sa.SmallInteger(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('debt_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archimate_id')
    )
    op.create_index('idx_system_archimate', 'system', ['archimate_id'], unique=False)
    op.create_index('idx_system_lifecycle', 'system', ['lifecycle_status'], unique=False)
    op.create_table('assessment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('assessment_mode', sa.String(), nullable=False),
    sa.Column('selected_perspectives', sa.JSON(), nullable=True),
    sa.Column('triage_treatment', sa.String(), nullable=False),
    sa.Column('triage_reason', sa.Text(), nullable=True),
    sa.Column('biv_b', sa.SmallInteger(), nullable=False),
    sa.Column('biv_i', sa.SmallInteger(), nullable=False),
    sa.Column('biv_v', sa.SmallInteger(), nullable=False),
    sa.Column('biv_rpo', sa.String(), nullable=True),
    sa.Column('biv_rto', sa.String(), nullable=True),
    sa.Column('zira_domain', sa.String(), nullable=True),
    sa.Column('zira_positioning', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('board_time_est', sa.String(), nullable=True),
    sa.Column('persona_version', sa.String(), nullable=False),
    sa.Column('persona_hash', sa.String(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('diagrams', sa.JSON(), nullable=True),
    sa.Column('principetoets', sa.JSON(), nullable=True),
    sa.Column('risk_register', sa.JSON(), nullable=True),
    sa.Column('citation_appendix', sa.Text(), nullable=True),
    sa.Column('clarification_questions', sa.JSON(), nullable=True),
    sa.Column('delta_changes', sa.JSON(), nullable=True),
    sa.Column('reassessed_perspectives', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('request_id', 'version')
    )
    op.create_index('idx_assessment_parent', 'assessment', ['parent_id'], unique=False)
    op.create_index('idx_assessment_request', 'assessment', ['request_id'], unique=False)
    op.create_table('clarification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('persona_role', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(length=36), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answered_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clarification_request', 'clarification', ['request_id'], unique=False)
    op.create_table('system_relationship',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('source_model', sa.String(), nullable=False),
    sa.Column('cascade_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['system.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relationship_type', 'source_model')
    )
    op.create_index('idx_rel_source', 'system_relationship', ['source_id'], unique=False)
    op.create_index('idx_rel_target', 'system_relationship', ['target_id'], unique=False)
    op.create_table('architecture_debt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('archimate_element_id', sa.String(), nullable=True),
    sa.Column('debt_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolves_via', sa.String(length=36), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolves_via'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debt_system', 'architecture_debt', ['system_id'], unique=False)
    op.create_table('board_decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('board_time_actual', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_assessment', 'board_decision', ['assessment_id'], unique=False)
    op.create_table('persona_finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('perspective_id', sa.String(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('persona_role', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('authority_type', sa.String(), nullable=True),
    sa.Column('authority_triggered', sa.Boolean(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('hidden_concern', sa.Text(), nullable=True),
    sa.Column('strongest_objection', sa.Text(), nullable=True),
    sa.Column('knowledge_bundle_ids', sa.JSON(), nullable=True),
    sa.Column('landscape_context_applied', sa.JSON(), nullable=True),
    sa.Column('persona_version', sa.String(), nullable=True),
    sa.Column('board_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.String(length=36), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['overridden_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_finding_assessment', 'persona_finding', ['assessment_id'], unique=False)
    op.create_index('idx_finding_rating', 'persona_finding', ['rating'], unique=False)
    op.create_table('retrospective',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.Column('finding_outcomes', sa.JSON(), nullable=True),
    sa.Column('condition_outcomes', sa.JSON(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('unpredicted_events', sa.JSON(), nullable=True),
    sa.Column('calibration_recommendations', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retrospective_assessment', 'retrospective', ['assessment_id'], unique=False)
    op.create_table('authority_action',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('requires_sign_off', sa.String(), nullable=False),
    sa.Column('sign_off_status', sa.String(), nullable=False),
    sa.Column('signed_off_by', sa.String(length=36), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sign_off_notes', sa.Text(), nullable=True),
    sa.Column('pipeline_halted', sa.Boolean(), nullable=False),
    sa.Column('halt_reason', sa.Text(), nullable=True),
    sa.Column('draft_disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['persona_finding.id'], ),
    sa.ForeignKeyConstraint(['signed_off_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authority_assessment', 'authority_action', ['assessment_id'], unique=False)
    op.create_index('idx_authority_signoff', 'authority_action', ['sign_off_status'], unique=False)
    op.create_table('board_override',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('original_rating', sa.String(), nullable=False),
    sa.Column('override_decision', sa.String(), nullable=False),
    sa.Column('override_reason', sa.String(), nullable=False),
    sa.Column('overridden_by', sa.String(length=36), nullable=False),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrospective_validated', sa.Boolean(), nullable=True),
    sa.Column('retrospective_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['board_decision.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['persona_finding.id'], ),
    sa.ForeignKeyConstraint(['overridden_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_override_finding', 'board_override', ['finding_id'], unique=False)
    op.create_table('citation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_failure', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['persona_finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_citation_assessment', 'citation', ['assessment_id'], unique=False)
    op.create_index('idx_citation_source', 'citation', ['source_type', 'source_id'], unique=False)
    op.create_table('condition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('source_persona', sa.String(), nullable=False),
    sa.Column('source_finding_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('escalation_to', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_finding_id'], ['persona_finding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_condition_assessment', 'condition', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_condition_assessment', table_name='condition')
    op.drop_table('condition')
    op.drop_index('idx_citation_source', table_name='citation')
    op.drop_index('idx_citation_assessment', table_name='citation')
    op.drop_table('citation')
    op.drop_index('idx_override_finding', table_name='board_override')
    op.drop_table('board_override')
    op.drop_index('idx_authority_signoff', table_name='authority_action')
    op.drop_index('idx_authority_assessment', table_name='authority_action')
    op.drop_table('authority_action')
    op.drop_index('idx_retrospective_assessment', table_name='retrospective')
    op.drop_table('retrospective')
    op.drop_index('idx_finding_rating', table_name='persona_finding')
    op.drop_index('idx_finding_assessment', table_name='persona_finding')
    op.drop_table('persona_finding')
    op.drop_index('idx_decision_assessment', table_name='board_decision')
    op.drop_table('board_decision')
    op.drop_index('idx_debt_system', table_name='architecture_debt')
    op.drop_table('architecture_debt')
    op.drop_index('idx_rel_target', table_name='system_relationship')
    op.drop_index('idx_rel_source', table_name='system_relationship')
    op.drop_table('system_relationship')
    op.drop_index('idx_clarification_request', table_name='clarification')
    op.drop_table('clarification')
    op.drop_index('idx_assessment_request', table_name='assessment')
    op.drop_index('idx_assessment_parent', table_name='assessment')
    op.drop_table('assessment')
    op.drop_index('idx_system_lifecycle', table_name='system')
    op.drop_index('idx_system_archimate', table_name='system')
    op.drop_table('system')
    op.drop_table('request')
    op.drop_index('idx_knowledge_type', table_name='knowledge_source')
    op.drop_table('knowledge_source')
    op.drop_index('idx_audit_type', table_name='audit_log')
    op.drop_index('idx_audit_assessment', table_name='audit_log')
    op.drop_index('idx_audit_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('vendor')
    op.drop_table('user')
    op.drop_table('persona_version')
    op.drop_table('persona_calibration')
    op.drop_index('idx_chunk_type', table_name='knowledge_chunk')
    op.drop_index('idx_chunk_source', table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    # ### end Alembic commands ###
