"""
Preflight synthesis engine — templates, citations, documents.

Port of synthesis/engine.mjs to idiomatic Python.
Templates are Markdown files with Jinja2-style {{ placeholder }} syntax.
Citations use [§P:name] and [§K:id] format.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

TEMPLATES_DIR = Path(__file__).parent.parent.parent.parent / "templates"

RATING_NL = {
    "approve": "Akkoord",
    "conditional": "Voorwaardelijk",
    "concern": "Bezorgd",
    "block": "Blokkade",
    "na": "N.v.t.",
}

AUTHORITY_NL = {
    "VETO": "Vetorecht",
    "ESCALATION": "Escalatie",
    "INDEPENDENT": "Onafhankelijk",
    "CHALLENGE": "Aanvechtging",
    "PATIENT_SAFETY": "Patiëntveiligheid",
}

ACCOUNTABILITY_DISCLAIMER = (
    "> **Disclaimer:** This is a draft assessment generated by Preflight using AI personas.\n"
    "> The architect owns the final assessment. The board owns the decision.\n"
    "> Preflight provides analysis, not judgment. All findings require human verification.\n"
    "> Citations marked [§P:name] come from persona assessments. "
    "Citations marked [§K:id] come from the knowledge base.\n"
    "> Uncited claims are flagged with [VERIFY] and must be confirmed by the architect."
)


# ---------------------------------------------------------------------------
# Template loading & resolution
# ---------------------------------------------------------------------------


def load_template(name: str) -> str:
    path = TEMPLATES_DIR / f"{name}.md"
    return path.read_text(encoding="utf-8")


def resolve_placeholders(template: str, context: dict[str, Any]) -> str:
    def _resolve(obj: Any, path: str) -> Any:
        for key in path.split("."):
            if isinstance(obj, dict):
                obj = obj.get(key)
            else:
                return None
        return obj

    def _replace(match: re.Match) -> str:
        path = match.group(1)
        value = _resolve(context, path)
        return str(value) if value is not None else match.group(0)

    return re.sub(r"\{\{(\w[\w.]*)\}\}", _replace, template)


# ---------------------------------------------------------------------------
# Citation system
# ---------------------------------------------------------------------------


def cite_persona(name: str, field: str | None = None) -> str:
    if field:
        return f"[§P:{name}.{field}]"
    return f"[§P:{name}]"


def cite_knowledge(source_id: str, excerpt: str | None = None) -> str:
    if excerpt:
        return f'[§K:{source_id}: "{excerpt}"]'
    return f"[§K:{source_id}]"


@dataclass
class CitationResult:
    persona: list[dict] = field(default_factory=list)
    knowledge: list[dict] = field(default_factory=list)


def parse_citations(text: str) -> CitationResult:
    persona = [
        {"name": m.group(1), "field": m.group(2), "index": m.start()}
        for m in re.finditer(r"\[§P:([A-Za-z-]+)(?:\.([a-z]+))?\]", text)
    ]
    knowledge = [
        {"id": m.group(1), "excerpt": m.group(2), "index": m.start()}
        for m in re.finditer(r"\[§K:([a-z0-9-]+)(?:: \"([^\"]+)\")?\]", text)
    ]
    return CitationResult(persona=persona, knowledge=knowledge)


def strip_citations(text: str) -> str:
    text = re.sub(r"\[§P:[A-Za-z-]+(?:\.[a-z]+)?\]", "", text)
    text = re.sub(r"\[§K:[a-z0-9-]+(?:: \"[^\"]+\")?\]", "", text)
    return re.sub(r"  +", " ", text).strip()


def verify_citations(text: str, context: dict) -> dict:
    citations = parse_citations(text)
    participating = {pf["name"] for pf in context.get("persona_findings", [])}
    available_sources = {s["id"] for s in context.get("sources", [])}
    cited_personas = {c["name"] for c in citations.persona}
    cited_sources = {c["id"] for c in citations.knowledge}

    unreferenced = [
        f'Persona "{c["name"]}" cited but did not participate in assessment'
        for c in citations.persona
        if c["name"] not in participating
    ] + [
        f'Source "{c["id"]}" cited but not in retrieved knowledge'
        for c in citations.knowledge
        if c["id"] not in available_sources
    ]

    uncited = [p for p in participating if p not in cited_personas]

    return {
        "valid": len(unreferenced) == 0,
        "unreferenced": unreferenced,
        "uncited": uncited,
    }


def generate_citation_appendix(
    persona_findings: list[dict], sources: list[dict] | None = None
) -> str:
    lines = ["## Bronvermelding / Sources", ""]

    if persona_findings:
        lines += [
            "### Persoonlijke bronnen / Persona sources",
            "",
            "| Persona | Rol | Autoriteit |",
            "|---------|-----|------------|",
        ]
        for pf in persona_findings:
            authority = AUTHORITY_NL.get(pf.get("authority", ""), "-")
            lines.append(f"| {pf['name']} | {pf['role']} | {authority} |")
        lines.append("")

    if sources:
        lines += [
            "### Kennisbronnen / Knowledge sources",
            "",
            "| ID | Bron / Source | Type | Relevantie / Relevance |",
            "|----|---------------|------|------------------------|",
        ]
        for s in sources:
            lines.append(
                f"| {s['id']} | {s.get('title', s['id'])} | {s.get('type', '-')} | {s.get('relevance', '-')} |"
            )
        lines.append("")

    return "\n".join(lines)


def citation_constraint_prompt(
    persona_findings: list[dict] | None = None, sources: list[dict] | None = None
) -> str:
    names = ", ".join(pf["name"] for pf in (persona_findings or [])) or "(none)"
    ids = ", ".join(s["id"] for s in (sources or [])) or "(none)"

    return (
        f"CITATION RULES — YOU MUST FOLLOW THESE:\n\n"
        f"1. Every factual claim MUST cite its source.\n"
        f"2. Use [§P:PersonaName] for claims from persona assessments. Available: {names}.\n"
        f"3. Use [§K:source-id] for claims from knowledge retrieval. Available: {ids}.\n"
        f'4. If you cannot verify a claim from available sources, write "[VERIFY]" after it.\n'
        f"5. Do NOT fabricate source IDs. Only use sources listed above.\n"
        f"6. Do NOT make claims without citations. Uncited claims will be flagged for human review."
    )


# ---------------------------------------------------------------------------
# Context builder
# ---------------------------------------------------------------------------


def build_context(
    proposal_name: str = "[voorstel naam]",
    request_type: str = "new-application",
    ratings: dict[str, str] | None = None,
    persona_findings: list[dict] | None = None,
    triage: dict | None = None,
    zira: dict | None = None,
    biv: dict | None = None,
    assessment_mode: str = "fast",
    landscape: dict | None = None,
) -> dict[str, Any]:
    ratings = ratings or {}
    persona_findings = persona_findings or []
    triage = triage or {}
    zira = zira or {}
    biv = biv or {}

    today = date.today().isoformat()
    blocks = [p for p in persona_findings if p.get("rating") == "block"]
    conditions = [p for p in persona_findings if p.get("rating") == "conditional"]
    veto_used = next((p for p in blocks if p.get("authority") == "VETO"), None)
    escalation_used = next(
        (p for p in blocks if p.get("authority") == "ESCALATION"), None
    )
    fg_block = next((p for p in blocks if p.get("authority") == "INDEPENDENT"), None)

    return {
        "proposal_name": proposal_name,
        "date": today,
        "version": "0.1",
        "status": "DRAFT",
        "assessment_mode": "Deep (panel)"
        if assessment_mode == "deep"
        else "Fast (batched)",
        "psa_id": f"PSA-{today.replace('-', '')}",
        "biv_b": biv.get("B", "_"),
        "biv_i": biv.get("I", "_"),
        "biv_v": biv.get("V", "_"),
        "biv_rpo": biv.get("rpo", "[RPO]"),
        "biv_rto": biv.get("rto", "[RTO]"),
        "treatment": triage.get("treatment", "[triage]"),
        "triage_reason": triage.get("reason", ""),
        "recommendation": _derive_recommendation(ratings, blocks),
        "board_time": _derive_board_time(ratings, triage),
        "zira_domain": zira.get(
            "domain", "[Zorg | Onderzoek | Onderwijs | Sturing | Bedrijfsondersteuning]"
        ),
        "zira_domain_secondary": zira.get("secondaryDomain", ""),
        "veto_exercised": f"Ja — door {veto_used['name']}: {(veto_used.get('findings') or [''])[0]}"
        if veto_used
        else "Nee",
        "escalation": f"Ja — door {escalation_used['name']}: {(escalation_used.get('findings') or [''])[0]}"
        if escalation_used
        else "Nee",
        "fg_determination": "Concept — bevestiging door FG vereist"
        if fg_block
        else "N.v.t.",
        "block_count": len(blocks),
        "condition_count": len(conditions),
    }


def _derive_recommendation(ratings: dict, blocks: list[dict]) -> str:
    if any(b.get("authority") in ("VETO", "INDEPENDENT") for b in blocks):
        return "Afwijzen"
    if blocks:
        return "Uitstellen"
    if sum(1 for r in ratings.values() if r == "concern") >= 2:
        return "Goedkeuren met voorwaarden"
    if any(r == "conditional" for r in ratings.values()):
        return "Goedkeuren met voorwaarden"
    return "Goedkeuren"


def _derive_board_time(ratings: dict, triage: dict) -> str:
    if triage.get("treatment") == "deep-review":
        return "volledige sessie"
    if triage.get("treatment") == "standard-review":
        return "30 min"
    return "15 min"


# ---------------------------------------------------------------------------
# Document generation
# ---------------------------------------------------------------------------


PRODUCT_TRIGGERS: dict[str, set[str]] = {
    "psa": {"always"},
    "adr": {"always"},
    "security-assessment": {"security-concern", "security-block"},
    "bia-biv": {"biv-high"},
    "dpia": {"patient-data", "clinical-system", "fg-dpo-concern", "fg-dpo-block"},
    "clinical-impact": {"clinical-system"},
    "integration-design": {"integration", "integration-concern", "integration-block"},
    "network-impact": {"network-concern", "network-block"},
    "process-impact": {"process-concern", "process-block"},
    "eu-ai-act": {"ai-ml"},
    "vendor-assessment": {"vendor-selection"},
    "nfr-specification": {"solution-concern", "solution-block"},
    "operational-readiness": {"always"},
    "tech-radar-update": {"new-application", "infrastructure-change"},
    "roadmap-impact": {"portfolio-concern", "portfolio-block", "architecture-roadmap"},
    "decommission-checklist": {"decommission"},
}


def determine_required_documents(
    request_type: str, ratings: dict[str, str] | None = None, biv: dict | None = None
) -> list[str]:
    ratings = ratings or {}
    biv = biv or {}

    active_triggers: set[str] = {"always", request_type}

    for persona_id, rating in ratings.items():
        if rating in ("block", "concern"):
            active_triggers.add(f"{persona_id}-block")
            active_triggers.add(f"{persona_id}-concern")

    if any(biv.get(k, 0) >= 3 for k in ("B", "I", "V")):
        active_triggers.add("biv-high")

    docs: set[str] = set()
    for doc_name, triggers in PRODUCT_TRIGGERS.items():
        if active_triggers & triggers:
            docs.add(doc_name)

    return sorted(docs)


def generate_document(template_name: str, context: dict) -> str:
    template = load_template(template_name)
    return resolve_placeholders(template, context)


def generate_all_documents(input: dict) -> dict[str, str]:
    context = build_context(
        **{
            k: v
            for k, v in input.items()
            if k
            in (
                "proposal_name",
                "request_type",
                "ratings",
                "persona_findings",
                "triage",
                "zira",
                "biv",
                "assessment_mode",
                "landscape",
            )
        }
    )
    required = determine_required_documents(
        input.get("request_type", "new-application"),
        input.get("ratings"),
        input.get("biv"),
    )

    documents = {}
    for name in required:
        try:
            documents[name] = generate_document(name, context)
        except FileNotFoundError:
            pass

    return documents


# ---------------------------------------------------------------------------
# Persona findings, risk register, conditions — for PSA sections
# ---------------------------------------------------------------------------


def format_persona_findings(persona_findings: list[dict]) -> str:
    sections = []
    overview_rows = []

    for i, pf in enumerate(persona_findings):
        name = pf.get("name", "?")
        role = pf.get("role", "?")
        rating = pf.get("rating", "?")
        authority = pf.get("authority")
        rating_nl = RATING_NL.get(rating, rating)

        sections.append(f"### 6.{i + 1} {name} — {role}")
        sections.append("")
        sections.append(f"**Beoordeling / Rating:** {rating_nl}")
        sections.append("")

        findings = pf.get("findings", [])
        if findings:
            sections.append("**Bevindingen / Findings:**")
            for f in findings:
                sections.append(f"- {f}")
            sections.append("")

        conditions = pf.get("conditions", [])
        if conditions:
            sections.append("**Voorwaarden / Conditions:**")
            for c in conditions:
                sections.append(f"- {c}")
            sections.append("")

        sections.append("---")
        sections.append("")

        authority_nl = AUTHORITY_NL.get(authority, "-") if authority else "-"
        overview_rows.append(f"| {role} | {name} | {rating_nl} | {authority_nl} |")

    overview = [
        "### Beoordelingsoverzicht / Assessment Overview",
        "",
        "| Persona | Naam | Rating | Bijzondere bevoegdheid |",
        "|---------|------|--------|------------------------|",
        *overview_rows,
        "",
    ]

    return "\n".join([*overview, *sections])


def generate_risk_register(persona_findings: list[dict]) -> str:
    rows = []
    n = 1
    for pf in persona_findings:
        if pf.get("rating") in ("approve", "na"):
            continue
        for finding in pf.get("findings", []):
            risk = "H" if pf["rating"] == "block" else "M"
            rows.append(
                f"| R{n} | {finding} | {risk} | {risk} | {risk} | {pf['name']} | [mitigerende maatregel] |"
            )
            n += 1

    if not rows:
        return "| # | Risico | Kans | Impact | Score | Bron (persona) | Mitigatie |\n|---|--------|------|--------|-------|----------------|-----------|\n| - | Geen risico's geïdentificeerd | - | - | - | - | - |"

    header = "| # | Risico | Kans | Impact | Score | Bron (persona) | Mitigatie |\n|---|--------|------|--------|-------|----------------|-----------|"
    return f"{header}\n" + "\n".join(rows)


def generate_conditions_table(persona_findings: list[dict]) -> str:
    rows = []
    n = 1
    for pf in persona_findings:
        for cond in pf.get("conditions", []):
            rows.append(
                f"| C{n} | {cond} | {pf['name']} | [eigenaar] | [datum] | Open |"
            )
            n += 1

    if not rows:
        return "| # | Voorwaarde | Bron (persona) | Eigenaar | Deadline | Status |\n|---|-----------|----------------|----------|----------|--------|\n| - | Geen voorwaarden | - | - | - | - |"

    header = "| # | Voorwaarde | Bron (persona) | Eigenaar | Deadline | Status |\n|---|-----------|----------------|----------|----------|--------|"
    return f"{header}\n" + "\n".join(rows)


def append_disclaimer(text: str) -> str:
    return f"{text}\n\n---\n\n{ACCOUNTABILITY_DISCLAIMER}"
